### ISSUE TITLE
nhentai无法打开

### ISSUE THREAD

**Issue by huangshengshi** [Pacalini/PicaComic#34] opened 2024-11-11 09:27 UTC
### 描述/Description

如题
![1000010019](https://github.com/user-attachments/assets/4a7d0891-9103-4dae-b5b7-55db613979f4)

### Version

4.1.6

### 使用的操作系统/Operating system

Android

### 日志/logs

Invalid Status Code: 404. Not found.
#0      ImageManager.getImage (package:pica_comic/foundation/image_manager.dart:136)
<asynchronous suspension>
#1      ReadingData.loadImage (package:pica_comic/pages/reader/reading_data.dart:57)
<asynchronous suspension>
#2      StreamImageProvider.load (package:pica_comic/foundation/image_loader/stream_image_provider.dart:29)
<asynchronous suspension>
#3      BaseImageProvider._loadBufferAsync (package:pica_comic/foundation/image_loader/base_image_provider.dart:53)
<asynchronous suspension>
#4      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013)
<asynchronous suspension>

**Comment by Pacalini** [comment] 2024-11-12 07:23
Duplicate of #31

**Closed by Pacalini** 2024-11-12 07:23 UTC
